modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="leather_craft"
version="1.4.0"
displayName="Leather Craft"
updateJSONURL="https://api.cfwidget.com/624669"
displayURL="https://www.anchorstudios.site"
logoFile="logo.png"
credits="Special thanks to everyone who contributed with their support, feedback and collaboration."
authors="Anchor Studios"
description="Allows you to create leather by smelting rotten flesh. It basically adds a recipe for it."
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.leather_craft]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.101-beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.leather_craft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration